name: finesse
channels:
- conda-forge
dependencies:
  - python=3.9
  - numpy >= 1.20
  - scipy >= 1.4
  - tqdm >= 4.40
  - h5py >= 3.0
  - matplotlib >=3.5
  - jupyter
  - networkx >= 2.4
  - sly >= 0.4
  - click >= 7.1
  - click-default-group >= 1.2.2
  - tabulate >= 0.8.7
  - control >= 0.9
  - sympy >= 1.6
  - deprecated >= 1.2
  - pyspellchecker >= 0.6
  - more-itertools >= 8.7
  - finesse
